### ISSUE TITLE
Status of the project?

### ISSUE THREAD

**Issue by NickSeagull** [serras/hinc#1]
Hey! This project is awesome as I have thought on creating something like this a lot of time through this last year and [I have drafted a couple of ideas on this subject](https://github.com/cloak-lang/cloak/issues?page=1&q=is%3Aissue+is%3Aopen). 

Is this a toy project? Or you planning on keep working on it? I'd like to help making this language a reality 😊

Also, I thought that providing a "base opinion" on the language as a guideline would be great. Something like favoring MTL, Effects, Components, or whatever over the other alternatives. This could make people using this language faster

Another goal was also to make it work as a GHC preprocessor, so we can benefit from the tooling like Cabal and alike.

No need to answer all these last thoughts, I just wanted to leave them here to give some context to my thoughts.

If you plan on keep working on this, we can open more issues to discuss all these things separately.
And if not, can I fork this to use it as a baseline? You would maintain credit for this of course 😃

Thanks a lot 🙏

**Comment by serras** [comment]
Hey, you discovered this before it was made public!

Right now my goal is to gather opinions from people, and at the same time make it usable as a GHC preprocessor. The `why.md` file has most of the ideas, but mainly the goal is to reduce the gap between effectful/non-effectful code, and have some nice syntax like intertwined arguments names and types.

The initial goalpost is to be able to express most of the term-level Haskell in this language. For that I still need to implement `data`, `class`, and `instance`, but that's a matter of a time (and luckily tomorrow I begin my holidays, so I should have plenty of it!). In particular, I haven't thought about favoring a particular style, although special support for lenses/prisms/traversals has crossed my mind.

I'd love to hear your thoughts! I'm sure you have plenty of cool ideas :)

**Comment by NickSeagull** [comment]
Sounds great! 

Yep, lens support was one of the first things I thought about. I saw you use `.` as `&`, but in my mind it was a sugar over `generic-lens` (which would be cooked into the language's standard library) [see this issue](https://github.com/cloak-lang/cloak/issues/16)

I have some more issues regarding those 3 you mention:
* [data](https://github.com/cloak-lang/cloak/issues/15)
* [class and instance](https://github.com/cloak-lang/cloak/issues/17)
* [derive](https://github.com/cloak-lang/cloak/issues/38)

**Comment by NickSeagull** [comment]
Closing this as the status is pretty clear :D
